# ---------- Stage 1: Builder ----------
FROM golang:1.24.6-alpine AS builder

WORKDIR /app

# Copy go.mod and go.sum to leverage caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the full source code
COPY . .

# Build static binary (recommended)
RUN CGO_ENABLED=0 GOOS=linux go build -o auth main.go


# ---------- Stage 2: Final Runtime ----------
FROM alpine:3.20

# Create app directory
WORKDIR /app
RUN mkdir -p /app/data

# Copy only the final compiled binary
COPY --from=builder /app/auth .

# Copy .env
COPY .env .

# Expose port
EXPOSE 8080

# Run the service
CMD ["./auth"]
