# Etapa 1: Builder
FROM golang:1.24.6-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o kpis main.go


# Etapa 2: Imagen final mínima
FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/kpis ./kpis

EXPOSE 8080

CMD ["./kpis"]
