# Etapa 1: Builder
FROM golang:1.24.6-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o Registro main.go


# Etapa 2: Imagen final mínima
FROM alpine:3.20

WORKDIR /app

# Crear carpeta para la base de datos dentro del contenedor
RUN mkdir -p /app/data

# Copiar base de datos inicial solo si decides no usar volumen
# COPY usuarios.db /app/data/usuarios.db

COPY --from=builder /app/Registro ./Registro

# Copy .env
COPY .env .

EXPOSE 8080

CMD ["./Registro"]
