# Etapa 1: Builder
FROM golang:1.24.6-alpine AS builder

WORKDIR /app

# Copiar dependencias del módulo
COPY go.mod go.sum ./
RUN go mod download

# Copiar todo el código
COPY . .

# Compilar el servicio
RUN go build -o ventas main.go


# Etapa 2: Imagen final mínima
FROM alpine:3.20

WORKDIR /app

# Copiar el binario generado
COPY --from=builder /app/ventas ./ventas

# Copiar el archivo de datos requerido
COPY Ventas.xlsx ./Ventas.xlsx

EXPOSE 8080

CMD ["./ventas"]
